### ISSUE TITLE
Angular Materialで画面の見た目をお洒落にする

### ISSUE THREAD

**Issue by yoshimi0227** [Doi-Ken/SpajamFront#11]
以下のサイトを参考に、画面をお洒落にする
https://material.angular.io/

https://qiita.com/donuzium/items/c9af982b02a9c4a2aaa8

**Comment by Doi-Ken** [comment]
ぜひやってほしいけど
ionicのようにNative環境でレンダリングできるか検証が必要

**Comment by yoshimi0227** [comment]
たしかに。

ステップ
1. サンプルを作成し、スマホ画面で反映されるか確認
2. どういう画面にしたいかメンバーに確認（ポップ、クール、シンプルなど）
3. イメージカラー決定。パワポ資料とあわせてプロトタイプ作成。
